customhost = "yoge-family.cjd4woj1ez0r.ap-south-1.rds.amazonaws.com"
customuser = "yogefamily"
custompass = "yogefamily"
customdb = "yoge-family"
custombucket = "firstfamily"
customregion = "ap-south-1"
